import Head from 'next/head'
import { getStoryblokApi, StoryblokComponent, useStoryblokState } from "@storyblok/react"

export default function Home({ story }:any) {
  story = useStoryblokState(story);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
     <header>
        <h1>
          { story ? story.name : 'My Site' }
        </h1>
      </header>
      <StoryblokComponent blok={story.content} />
     </main>
    </>
  )
}

export async function getStaticProps() {
  // home is the default slug for the homepage in Storyblok
  let slug = "home";
 
  // load the draft version
  let sbParams = {
    version: "draft", // or 'published'
  };
 
  const storyblokApi = getStoryblokApi();
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams as any);
 
  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
    },
    revalidate: 3600, // revalidate every hour
  };
}
